version: '3'

services:
  db:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: local
      POSTGRES_USER: payload
      POSTGRES_DB: payload
volumes:
  node_modules:
